# Generated by Django 4.1.9 on 2023-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=10)),
                ('edad', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'usuarioDB',
            },
        ),
    ]
