# Generated by Django 4.1.10 on 2023-08-20 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_reda_Comet', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=500)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('replicas', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
            options={
                'db_table': 'comentariosDB',
            },
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'credencialesDB',
            },
        ),
        migrations.CreateModel(
            name='Replicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRedactorReplica', models.CharField(max_length=100)),
                ('contenidoReplica', models.CharField(max_length=600)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('genero', models.CharField(max_length=1, null=True)),
                ('url_imagen_perfil', models.CharField(max_length=300, null=True)),
                ('code_delete_img', models.CharField(max_length=300, null=True)),
                ('conversaciones', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None)),
            ],
            options={
                'db_table': 'usuarioDB',
            },
        ),
    ]
