# Generated by Django 4.1.10 on 2023-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credenciales',
            name='clave',
        ),
        migrations.AddField(
            model_name='credenciales',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='credenciales',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='correo',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='credenciales',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
